// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'models/card'], function(Backbone, Card) {
    var CardCollection;
    return CardCollection = (function(_super) {

      __extends(CardCollection, _super);

      function CardCollection() {
        return CardCollection.__super__.constructor.apply(this, arguments);
      }

      CardCollection.prototype.model = Card;

      CardCollection.prototype.url = function() {
        return "https://trello.com/1/lists/" + this.listId + "/cards?key=" + (localStorage.getItem('trelloKey')) + "&token=" + (localStorage.getItem('trelloToken'));
      };

      return CardCollection;

    })(Backbone.Collection);
  });

}).call(this);
