// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'models/comment'], function(Backbone, Comment) {
    var CommentsCollection;
    return CommentsCollection = (function(_super) {

      __extends(CommentsCollection, _super);

      function CommentsCollection() {
        return CommentsCollection.__super__.constructor.apply(this, arguments);
      }

      CommentsCollection.prototype.model = Comment;

      return CommentsCollection;

    })(Backbone.Collection);
  });

}).call(this);
