// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'models/list'], function(Backbone, List) {
    var ListsCollection;
    return ListsCollection = (function(_super) {

      __extends(ListsCollection, _super);

      function ListsCollection() {
        return ListsCollection.__super__.constructor.apply(this, arguments);
      }

      ListsCollection.prototype.model = List;

      ListsCollection.prototype.url = function() {
        return "https://trello.com/1/boards/" + this.boardId + "/lists?key=" + (localStorage.getItem('trelloKey')) + "&token=" + (localStorage.getItem('trelloToken'));
      };

      return ListsCollection;

    })(Backbone.Collection);
  });

}).call(this);
