// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'models/member'], function(Backbone, Member) {
    var MembersCollection;
    return MembersCollection = (function(_super) {

      __extends(MembersCollection, _super);

      function MembersCollection() {
        return MembersCollection.__super__.constructor.apply(this, arguments);
      }

      MembersCollection.prototype.model = Member;

      return MembersCollection;

    })(Backbone.Collection);
  });

}).call(this);
