// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'models/organization'], function(Backbone, Organization) {
    var OrganizationCollection;
    OrganizationCollection = (function(_super) {

      __extends(OrganizationCollection, _super);

      function OrganizationCollection() {
        return OrganizationCollection.__super__.constructor.apply(this, arguments);
      }

      OrganizationCollection.prototype.model = Organization;

      OrganizationCollection.prototype.url = function() {
        return "https://trello.com/1/members/me/organizations?key=" + (localStorage.getItem('trelloKey')) + "&token=" + (localStorage.getItem('trelloToken'));
      };

      return OrganizationCollection;

    })(Backbone.Collection);
    return OrganizationCollection;
  });

}).call(this);
