// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'jquery', 'underscore', 'collections/boards', 'collections/organizations', 'views/boards_view', 'views/home_tabs', 'views/organizations_view'], function(Backbone, $, _, BoardsCollection, OrganizationsCollection, BoardsView, HomeTabsView, OrganizationsView) {
    var AppRouter;
    AppRouter = (function(_super) {

      __extends(AppRouter, _super);

      function AppRouter() {
        return AppRouter.__super__.constructor.apply(this, arguments);
      }

      AppRouter.prototype.routes = {
        "boards": "getMyBoards",
        "organizations": "getMyOrganizations",
        "*actions": "getMyBoards"
      };

      AppRouter.prototype.getMyBoards = function() {
        var boardsList, list, tabs;
        console.log("boards");
        boardsList = new BoardsCollection;
        list = new BoardsView({
          model: boardsList,
          el: $("#screen")
        });
        boardsList.fetch();
        tabs = new HomeTabsView("boards");
        return $("#menu").html(tabs.el);
      };

      AppRouter.prototype.getMyOrganizations = function() {
        var list, organizationsList;
        organizationsList = new OrganizationsCollection;
        list = new OrganizationsView({
          model: organizationsList,
          el: $("#screen")
        });
        return organizationsList.fetch();
      };

      return AppRouter;

    })(Backbone.Router);
    return AppRouter;
  });

}).call(this);
