// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'collections/lists'], function(Backbone, ListsCollection) {
    var Board;
    Board = (function(_super) {

      __extends(Board, _super);

      function Board() {
        return Board.__super__.constructor.apply(this, arguments);
      }

      Board.prototype.url = function() {
        return "https://trello.com/1/boards/" + this.id + "?key=" + (localStorage.getItem('trelloKey')) + "&token=" + (localStorage.getItem('trelloToken'));
      };

      Board.prototype.initialize = function() {
        this.lists = new ListsCollection;
        return this.lists.boardId = this.id;
      };

      return Board;

    })(Backbone.Model);
    return Board;
  });

}).call(this);
