// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'models/member', 'collections/comments', 'collections/checklists'], function(Backbone, Member, CommentsCollection, ChecklistsCollection) {
    var Card;
    return Card = (function(_super) {

      __extends(Card, _super);

      function Card() {
        return Card.__super__.constructor.apply(this, arguments);
      }

      Card.prototype.url = function() {
        return "https://trello.com/1/cards/" + this.id + "?key=" + (localStorage.getItem('trelloKey')) + "&token=" + (localStorage.getItem('trelloToken'));
      };

      Card.prototype.initialize = function() {
        this.comments = new CommentsCollection;
        this.comments.url = "https://api.trello.com/1/cards/" + this.id + "/actions?type=commentCard&key=" + (localStorage.getItem('trelloKey')) + "&token=" + (localStorage.getItem('trelloToken'));
        this.checklists = new ChecklistsCollection;
        return this.checklists.url = "https://api.trello.com/1/cards/" + this.id + "/checklists?type=commentCard&key=" + (localStorage.getItem('trelloKey')) + "&token=" + (localStorage.getItem('trelloToken'));
      };

      return Card;

    })(Backbone.Model);
  });

}).call(this);
