// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone'], function(Backbone) {
    var Member;
    return Member = (function(_super) {

      __extends(Member, _super);

      function Member() {
        return Member.__super__.constructor.apply(this, arguments);
      }

      Member.prototype.url = function() {
        return "https://trello.com/1/members/" + this.id + "?key=" + (localStorage.getItem('trelloKey')) + "&token=" + (localStorage.getItem('trelloToken'));
      };

      return Member;

    })(Backbone.RelationalModel);
  });

}).call(this);
