// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone'], function(Backbone) {
    var Notification;
    return Notification = (function(_super) {

      __extends(Notification, _super);

      function Notification() {
        return Notification.__super__.constructor.apply(this, arguments);
      }

      Notification.prototype.humanize = function() {
        return "testop";
      };

      return Notification;

    })(Backbone.Model);
  });

}).call(this);
