// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'models/member', 'collections/members'], function(Backbone, Member, MembersCollection) {
    var Organization;
    return Organization = (function(_super) {

      __extends(Organization, _super);

      function Organization() {
        return Organization.__super__.constructor.apply(this, arguments);
      }

      Organization.prototype.relations = [
        {
          type: Backbone.HasMany,
          key: 'memberships',
          relatedModel: Member,
          collectionType: MembersCollection,
          reverseRelation: {
            key: 'organization',
            includeInJSON: 'id'
          }
        }
      ];

      return Organization;

    })(Backbone.RelationalModel);
  });

}).call(this);
