// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore', 'views/boards_view_item', 'text!templates/boards_view.html'], function($, Backbone, _, BoardsViewItem, template) {
    var BoardsView;
    return BoardsView = (function(_super) {

      __extends(BoardsView, _super);

      function BoardsView() {
        return BoardsView.__super__.constructor.apply(this, arguments);
      }

      BoardsView.prototype.template = _.template(template);

      BoardsView.prototype.initialize = function() {
        this.render();
        return this.model.on("reset", this.render, this);
      };

      BoardsView.prototype.render = function() {
        $(this.el).empty();
        _.each(this.model.models, function(singleModel) {
          return this.renderOne(singleModel);
        }, this);
        return bb.imageList.apply($("#screen"));
      };

      BoardsView.prototype.renderOne = function(singleModel) {
        var board;
        board = new BoardsViewItem({
          model: singleModel
        });
        return $(this.el).append(board.render().el);
      };

      return BoardsView;

    })(Backbone.View);
  });

}).call(this);
