// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore', 'views/board_cards_tab_view_item', 'text!templates/board_cards_tab.html'], function($, Backbone, _, BoardCardsTabsViewItem, template) {
    var BoardCardsTabsView;
    return BoardCardsTabsView = (function(_super) {

      __extends(BoardCardsTabsView, _super);

      function BoardCardsTabsView() {
        return BoardCardsTabsView.__super__.constructor.apply(this, arguments);
      }

      BoardCardsTabsView.prototype.initialize = function() {
        $("#menu").html(template);
        return this.render();
      };

      BoardCardsTabsView.prototype.render = function() {
        _.each(this.model.models, function(singleModel, key) {
          return this.renderOne(singleModel, key);
        }, this);
        return bb.actionBar.apply($("#actionbar")[0]);
      };

      BoardCardsTabsView.prototype.renderOne = function(singleModel, key) {
        var item;
        item = new BoardCardsTabsViewItem({
          model: singleModel
        });
        return $("#actionbar").append(item.render(key).el);
      };

      return BoardCardsTabsView;

    })(Backbone.View);
  });

}).call(this);
