// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore', 'views/board_view', 'text!templates/boards_item_view.html'], function($, Backbone, _, BoardView, template) {
    var ListViewItem;
    ListViewItem = (function(_super) {

      __extends(ListViewItem, _super);

      function ListViewItem() {
        return ListViewItem.__super__.constructor.apply(this, arguments);
      }

      ListViewItem.prototype.template = _.template(template);

      ListViewItem.prototype.events = {
        "click": "onClick"
      };

      ListViewItem.prototype.render = function() {
        $(this.el).html(this.template(this.model.toJSON()));
        return this;
      };

      ListViewItem.prototype.onClick = function() {
        return new BoardView({
          model: this.model
        });
      };

      return ListViewItem;

    })(Backbone.View);
    return ListViewItem;
  });

}).call(this);
