// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore', 'views/cards_view_item'], function($, Backbone, _, CardsViewItem) {
    var CardsView;
    return CardsView = (function(_super) {

      __extends(CardsView, _super);

      function CardsView() {
        return CardsView.__super__.constructor.apply(this, arguments);
      }

      CardsView.prototype.initialize = function() {
        this.render();
        return this.model.on("reset", this.render, this);
      };

      CardsView.prototype.render = function() {
        console.log(this.model);
        $(this.el).empty();
        _.each(this.model.models, function(singleModel) {
          return this.renderOne(singleModel);
        }, this);
        return bb.imageList.apply($("#screen"));
      };

      CardsView.prototype.renderOne = function(singleModel) {
        var board;
        board = new CardsViewItem({
          model: singleModel
        });
        return $(this.el).append(board.render().el);
      };

      return CardsView;

    })(Backbone.View);
  });

}).call(this);
