// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore', 'models/board', 'text!templates/card_edit.html', 'text!templates/card_edit/select_list.html', 'text!templates/card_edit/select_list_option.html'], function($, Backbone, _, Board, template, select_template, option_template) {
    var CardEditView;
    return CardEditView = (function(_super) {

      __extends(CardEditView, _super);

      function CardEditView() {
        return CardEditView.__super__.constructor.apply(this, arguments);
      }

      CardEditView.prototype.template = _.template(template);

      CardEditView.prototype.optionTemplate = _.template(option_template);

      CardEditView.prototype.events = {
        "click #titleBar": "doSave"
      };

      CardEditView.prototype.initialize = function() {
        this.board = new Board({
          id: this.model.get('idBoard')
        });
        this.board.lists.on("reset", this.renderLists, this);
        this.board.lists.fetch();
        return this.render();
      };

      CardEditView.prototype.render = function() {
        $(this.el).html(this.template(this.model.toJSON()));
        bb.titleBar.apply($("#titleBar")[0]);
        return bb.doLoad($("#screen")[0]);
      };

      CardEditView.prototype.renderLists = function() {
        $("#lists").append(select_template);
        _.each(this.board.lists.models, function(model) {
          return $("#cardList").append(this.optionTemplate(model.toJSON()));
        }, this);
        return bb.dropdown.apply($("#cardList"));
      };

      CardEditView.prototype.doSave = function() {
        alert("saving");
        this.model.set({
          name: $("cardNameInput"),
          desc: $("cardDescriptionInput")
        });
        this.model.save();
        return alert("saved");
      };

      return CardEditView;

    })(Backbone.View);
  });

}).call(this);
