// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore', 'collections/cards', 'views/cards_item_view'], function($, Backbone, _, CardsCollection, CardsItemView) {
    var CardsFromListView;
    return CardsFromListView = (function(_super) {

      __extends(CardsFromListView, _super);

      function CardsFromListView() {
        return CardsFromListView.__super__.constructor.apply(this, arguments);
      }

      CardsFromListView.prototype.initialize = function() {
        var lists;
        lists = new ListsCollection;
        lists.boardId = this.model.id;
        return lists.fetch({
          success: function(data) {
            console.log(data);
            return new BoardCardsTabsView({
              model: data
            });
          }
        });
      };

      CardsFromListView.prototype.renderOne = function(singleModel) {
        var view;
        view = new CardsItemView({
          model: singleModel
        });
        return $(this.el).append(view.render().el);
      };

      return CardsFromListView;

    })(Backbone.View);
  });

}).call(this);
