// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore', 'views/card_view', 'text!templates/cards_view_item.html'], function($, Backbone, _, CardView, item_template) {
    var CardsViewItem;
    return CardsViewItem = (function(_super) {

      __extends(CardsViewItem, _super);

      function CardsViewItem() {
        return CardsViewItem.__super__.constructor.apply(this, arguments);
      }

      CardsViewItem.prototype.template = _.template(item_template);

      CardsViewItem.prototype.events = {
        "click": "renderCard"
      };

      CardsViewItem.prototype.render = function() {
        $(this.el).html(this.template(this.model.toJSON()));
        return this;
      };

      CardsViewItem.prototype.renderCard = function() {
        var card;
        return card = new CardView({
          el: $("#screen"),
          model: this.model
        });
      };

      return CardsViewItem;

    })(Backbone.View);
  });

}).call(this);
