// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore', 'collections/checklists', 'text!templates/card_menu.html'], function($, Backbone, _, ChecklistsCollections, template) {
    var CardMenuView;
    return CardMenuView = (function(_super) {

      __extends(CardMenuView, _super);

      function CardMenuView() {
        return CardMenuView.__super__.constructor.apply(this, arguments);
      }

      CardMenuView.prototype.template = _.template(template);

      CardMenuView.prototype.initialize = function() {
        this.model.checklists.on("reset", this.render, this);
        this.model.checklists.fetch();
        return this.render();
      };

      CardMenuView.prototype.render = function() {
        console.log(this.model.checklists);
        $(this.el).html(this.template(this.model.checklists));
        return bb.actionBar.apply($(this.el)[0]);
      };

      return CardMenuView;

    })(Backbone.View);
  });

}).call(this);
