// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore', 'views/organization_view', 'text!templates/organizations_item_view.html'], function($, Backbone, _, OrganizationView, template) {
    var OrganizationsViewItem;
    return OrganizationsViewItem = (function(_super) {

      __extends(OrganizationsViewItem, _super);

      function OrganizationsViewItem() {
        return OrganizationsViewItem.__super__.constructor.apply(this, arguments);
      }

      OrganizationsViewItem.prototype.template = _.template(template);

      OrganizationsViewItem.prototype.events = {
        "click": "onClick"
      };

      OrganizationsViewItem.prototype.render = function() {
        $(this.el).html(this.template(this.model.toJSON()));
        return this;
      };

      OrganizationsViewItem.prototype.onClick = function() {
        return new OrganizationView({
          model: this.model,
          el: $("#screen")
        });
      };

      return OrganizationsViewItem;

    })(Backbone.View);
  });

}).call(this);
