// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore', 'text!templates/organization.html'], function($, Backbone, _, template) {
    var OrganizationView;
    return OrganizationView = (function(_super) {

      __extends(OrganizationView, _super);

      function OrganizationView() {
        return OrganizationView.__super__.constructor.apply(this, arguments);
      }

      OrganizationView.prototype.template = _.template(template);

      OrganizationView.prototype.initialize = function() {
        console.log(this.model.get('memberships'));
        return this.render();
      };

      OrganizationView.prototype.render = function() {
        $(this.el).html(this.template(this.model.toJSON()));
        bb.doLoad($("#screen")[0]);
        return bb.titleBar.apply($("#title")[0]);
      };

      return OrganizationView;

    })(Backbone.View);
  });

}).call(this);
