// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'underscore', 'views/organizations_view_item', 'text!templates/organizations_view.html'], function($, Backbone, _, OrganizationsViewItem, template) {
    var OrganizationsView;
    OrganizationsView = (function(_super) {

      __extends(OrganizationsView, _super);

      function OrganizationsView() {
        return OrganizationsView.__super__.constructor.apply(this, arguments);
      }

      OrganizationsView.prototype.template = _.template(template);

      OrganizationsView.prototype.initialize = function() {
        this.render();
        return this.model.on("reset", this.render, this);
      };

      OrganizationsView.prototype.render = function() {
        $(this.el).empty();
        _.each(this.model.models, function(singleModel) {
          return this.renderOne(singleModel);
        }, this);
        return bb.imageList.apply($("#screen"));
      };

      OrganizationsView.prototype.renderOne = function(singleModel) {
        var board;
        board = new OrganizationsViewItem({
          model: singleModel
        });
        return $(this.el).append(board.render().el);
      };

      return OrganizationsView;

    })(Backbone.View);
    return OrganizationsView;
  });

}).call(this);
